<template>
  <svg
    xmlns="http://www.w3.org/2000/svg"
    xmlns:xlink="http://www.w3.org/1999/xlink"
    style="margin: auto; background: none; display: block; shape-rendering: auto;"
    width="200px"
    height="200px"
    viewBox="0 0 100 100"
    preserveAspectRatio="xMidYMid"
  >
    <circle cx="84" cy="50" r="10" fill="#efe561">
      <animate
        attributeName="r"
        repeatCount="indefinite"
        dur="0.23584905660377356s"
        calcMode="spline"
        keyTimes="0;1"
        values="9;0"
        keySplines="0 0.5 0.5 1"
        begin="0s"
      />
      <animate
        attributeName="fill"
        repeatCount="indefinite"
        dur="0.9433962264150942s"
        calcMode="discrete"
        keyTimes="0;0.25;0.5;0.75;1"
        values="#efe561;#e9cc00;#f5be2a;#f8db0c;#efe561"
        begin="0s"
      />
    </circle>
    <circle cx="16" cy="50" r="10" fill="#efe561">
      <animate
        attributeName="r"
        repeatCount="indefinite"
        dur="0.9433962264150942s"
        calcMode="spline"
        keyTimes="0;0.25;0.5;0.75;1"
        values="0;0;9;9;9"
        keySplines="0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1"
        begin="0s"
      />
      <animate
        attributeName="cx"
        repeatCount="indefinite"
        dur="0.9433962264150942s"
        calcMode="spline"
        keyTimes="0;0.25;0.5;0.75;1"
        values="16;16;16;50;84"
        keySplines="0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1"
        begin="0s"
      />
    </circle>
    <circle cx="50" cy="50" r="10" fill="#f8db0c">
      <animate
        attributeName="r"
        repeatCount="indefinite"
        dur="0.9433962264150942s"
        calcMode="spline"
        keyTimes="0;0.25;0.5;0.75;1"
        values="0;0;9;9;9"
        keySplines="0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1"
        begin="-0.23584905660377356s"
      />
      <animate
        attributeName="cx"
        repeatCount="indefinite"
        dur="0.9433962264150942s"
        calcMode="spline"
        keyTimes="0;0.25;0.5;0.75;1"
        values="16;16;16;50;84"
        keySplines="0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1"
        begin="-0.23584905660377356s"
      />
    </circle>
    <circle cx="84" cy="50" r="10" fill="#f5be2a">
      <animate
        attributeName="r"
        repeatCount="indefinite"
        dur="0.9433962264150942s"
        calcMode="spline"
        keyTimes="0;0.25;0.5;0.75;1"
        values="0;0;9;9;9"
        keySplines="0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1"
        begin="-0.4716981132075471s"
      />
      <animate
        attributeName="cx"
        repeatCount="indefinite"
        dur="0.9433962264150942s"
        calcMode="spline"
        keyTimes="0;0.25;0.5;0.75;1"
        values="16;16;16;50;84"
        keySplines="0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1"
        begin="-0.4716981132075471s"
      />
    </circle>
    <circle cx="16" cy="50" r="10" fill="#e9cc00">
      <animate
        attributeName="r"
        repeatCount="indefinite"
        dur="0.9433962264150942s"
        calcMode="spline"
        keyTimes="0;0.25;0.5;0.75;1"
        values="0;0;9;9;9"
        keySplines="0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1"
        begin="-0.7075471698113207s"
      />
      <animate
        attributeName="cx"
        repeatCount="indefinite"
        dur="0.9433962264150942s"
        calcMode="spline"
        keyTimes="0;0.25;0.5;0.75;1"
        values="16;16;16;50;84"
        keySplines="0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1"
        begin="-0.7075471698113207s"
      />
    </circle>
    <!-- [ldio] generated by https://loading.io/ -->
  </svg>
</template>

<script>
export default {
  name: "LoaderSVG",
};
</script>
